# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: system
  color: blue

# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: 'Ehsan SadrFaridpour'
    description: 'Ehsan SadrFaridpour - Biomedical Data Science Researcher with expertise in scalable machine learning, AI, and predictive analytics.'
    twitter: 'SadrEhson'
  analytics:
    google_analytics: 'UA-12345678-1'
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: ''
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    blox: "navbar"
    fixed_to_top: true
    show_search: true
    show_theme_chooser: true
    logo:
      text: "Ehsan SadrFaridpour"

# Site footer
footer:
  copyright:
    notice: '© {year} Ehsan SadrFaridpour. This work is licensed under {license}'
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'

# Site features
features:
  math:
    enable: true
  privacy_pack:
    enable: false


comments:
  provider: giscus
  giscus:
    repo: "esadr/esadr.github.io"  # ✅ Replace with your actual GitHub repo
    repo_id: "MDEwOlJlcG9zaXRvcnkxMDQxMzM4NjU="  # ✅ Get this from the Giscus setup page (in the URL of the page)
    category: "q-a"  # ✅ Use the exact category name from your GitHub Discussions
    category_id: "DIC_kwDOBjT06c4CnIHT"  # ✅ Find this in the Giscus setup
    mapping: "pathname"  # ✅ Maps blog posts to discussions based on their URL
    theme: "preferred_color_scheme"  # ✅ Uses the user's preferred light/dark mode
    reactions_enabled: "1"  # ✅ Enables reaction emojis (👍, 🚀, ❤️)
    emit_metadata: "0"  # ✅ Set to "1" if you want additional metadata for SEO
    input_position: "bottom"  # ✅ Places the comment box at the bottom of the discussion

markup:
  goldmark:
    renderer:
      unsafe: true

comments: true
giscusTheme: preferred_color_scheme
disableComments: false